### ISSUE TITLE
Increase timeout or remove valgrind CI job?

### ISSUE THREAD

**Issue by dergoegge** [bitcoin-core/qa-assets#113]
I think there are only ~5 occurrences of the valgrind job passing out of all the merged/closed PRs. They always (afaict) fail due to timing out.

So maybe we should:
* Increase the timeout? (unless the job would take way to long anyway)
* Remove the job?
* Only run on corpora that were changed in a PR?

**Comment by fanquake** [comment]
We are currently [set at](https://github.com/bitcoin-core/qa-assets/blob/main/.cirrus.yml#L10) the limit of 120m for non-credit tasks, see https://cirrus-ci.org/faq/#instance-timed-out. Maybe we can use some compute credits.

**Comment by fanquake** [comment]
Relevant CI job now that credits PR has been merged: https://cirrus-ci.com/task/6079733960540160

**Comment by fanquake** [comment]
Looks like it is working:
![credits](https://user-images.githubusercontent.com/863730/233083527-638c8b33-dc99-4954-872e-91d6f5c89f61.png)

**Comment by fanquake** [comment]
> Relevant CI job now that credits PR has been merged: https://cirrus-ci.com/task/6079733960540160

Ultimately timed-out after 8 hours. However looking at the job, it also didn't use any compute credits?
![credits](https://user-images.githubusercontent.com/863730/233322920-a2291265-e2c1-49de-96f6-2af4c24ac36d.png)

**Comment by fanquake** [comment]
Don't know. I have refreshed multiple times, and am logged in. Nothing showing up.

**Comment by dergoegge** [comment]
Hm, the job still times out even with the credits, so maybe we should remove it from CI?

**Comment by fanquake** [comment]
Yea I'm happy for this to remain, even if it never quite completes, if we're running 95+% of targets.

**Comment by dergoegge** [comment]
Ok! Should we exclude the really slow targets from running then?

**Comment by dergoegge** [comment]
I find the red CI is super annoying because it has to be looked at every time and the slow targets still run in the other jobs (with MSan for example).

We could also setup our own remote runner (like you suggested earlier) but is that worth it?

**Comment by dergoegge** [comment]
Closing. 

I will setup a machine for the valgrind job sometime soon and then open a PR to no longer run it in CI here.

**Comment by dergoegge** [comment]
> So avoiding a red CI by all costs may not be a worthy goal?

My main concern with the red CI is that it **has** to be looked at, since the valgrind job either fails because of some bug or it times out and we definitely want to catch when there's a bug. I know it's easy to check but I just find it very annoying. I couldn't find this in the cirrus docs, but maybe there is an option to ignore timeouts?

Otherwise I think, we can just have one (or more) remote runners that publish the result to GitHub somehow, so we still get the green CI (I think I saw something about cirrus allowing remote runners). I am happy to set that up at some point and until then we keep it the way it is now.

> adding a script or CI task to check that a pull only adds files, not removes them. Such a task would then fail (red) if non-reduced and stale inputs are deleted.

Sounds good and this should only fail on that ~one pruning PR every 6 months.
