### ISSUE TITLE
brainstorm: Reducing the size of this repo

### ISSUE THREAD

**Issue by dergoegge** [bitcoin-core/qa-assets#130]
This repository is very large (~16GB atm) and I think there are a bunch of things we could do to improve that.

* Prune the git history,  `.git` is currently at 4GB. (we don't really need the history/we could archive to the history to a separate repo)
* Compress corpora (~6GB gzip)
* Avoid large inputs / have separate repo for those

The biggest downside to the size currently is that we pull this repo in our CI jobs (oss-fuzz as well) which is a big overhead.

Maybe we setup an automated mirror repo that has the compressed corpora and no git history?

**Comment by dergoegge** [comment]
@MarcoFalke thoughts?

**Comment by dergoegge** [comment]
I guess cloning with `--depth 1` already works quite well

**Comment by murchandamus** [comment]
Is `git` really the right tool to manage a data collection with so many files? Unfortunately, I don’t have a better idea (yet), but it does seem terribly slow in interactions with this repository.

**Comment by murchandamus** [comment]
It might be worth fuzzing with either `afl++` or `libfuzzer` but then only uploading what `afl-cmin` considers to be increasing coverage?

**Comment by dergoegge** [comment]
Just noting that the size of `fuzz_seed_corpus` is reduced to 1.6GB from 14GB using `afl-cmin`, coverage report: https://dergoegge.github.io/bitcoin-coverage/afl-cmin/fuzz.coverage/src/index.html

**Comment by dergoegge** [comment]
> How much would that be with libFuzzer with and without -use_value_profile?

8.1GB with, 1.9GB without.

So perhaps dropping `use_value_profile` from the merge script is the best low-effort solution for now?

**Comment by dergoegge** [comment]
> I am getting 1.6G vs 1.9G

Could you also test this with `-use_value_profile=1 -set_cover_merge=1`? Maybe that could be a nice middle ground...

**Comment by murchandamus** [comment]
For creating a new corpus at the branch-off point, would it perhaps make sense to at least combine the crème de la crème? I.e. if each of us merged their active fuzzing directory to a new directory with `-set_cover_merge` and pushed that branch to their own repos, someone could combine the old bloated set and our individual best sets to create the new starting point?

**Comment by murchandamus** [comment]
Oh, that’s an interesting thought. That might also explain why for me the `set_cover_merge` from my active fuzzing directory was bigger than the merge from active fuzzing + `qa-assets/main`.
