### ISSUE TITLE
Rename fuzz_seed_corpus?

### ISSUE THREAD

**Issue by maflcko** [bitcoin-core/qa-assets#200]
With the cmake-migration all fuzz scripts will have to be touched, which is probably the best time to rename the folder if there is desire to do so.

The current name is minimally confusing, because `seed` doesn't really apply. In reality it is a collection of fuzz input seeds, as well as fuzz inputs.

So my recommendation would be to just drop `seed`. This will also allow in the future (when there is a need and desire) to provide a minimal set of possibly hand-crafted or otherwise  non-fuzz-generated fuzz seed inputs to some fuzz targets (and possibly store them in a separate folder and validate that their format is still accurate and matches the fuzz target code). Even if this is never done, dropping `seed` may still be useful.

Also, `corpus` could be renamed to `corpora`, to clarify that the folder holds the fuzz inputs for several fuzz targets.

Thoughts?

**Comment by dergoegge** [comment]
ACK `fuzz_corpora`

**Comment by murchandamus** [comment]
Yay, `fuzz_corpora`!
